import type { Metadata } from 'next';
import { Inter, Nunito } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { GlobalContext } from '@/components/layout/GlobalContext';
import { Toaster } from '@/components/ui/sonner';
import { CartSheet } from '@/components/cart/CartSheet';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-inter',
  display: 'swap',
});

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Vyomvanta Traders',
  description: 'Generated by Shubham Mishra',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nunito.variable} antialiased`}>
        <GlobalContext>
          <Header />
          <CartSheet />
          {children}
          <Toaster />
          <Footer />
        </GlobalContext>
      </body>
    </html>
  );
}